#!/usr/bin/env bash

# add Postgres apt repo and bring apt up to date
sudo add-apt-repository "deb https://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
wget --quiet -O - https://postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update

# install Postgres
sudo apt-get -y install postgresql-9.4
sudo apt-get -y install postgresql-contrib-9.4 postgresql-server-dev-9.4
sudo -u postgres createuser -d -s django
sudo -u postgres createdb -O django audb
sudo cp /etc/postgresql/9.4/main/postgresql.conf /etc/postgresql/9.4/main/postgresql.conf_OLD
sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.4/main/pg_hba.conf_OLD
sudo cp /vagrant/vagrant-files/local-postgresql.conf /etc/postgresql/9.4/main/postgresql.conf
sudo cp /vagrant/vagrant-files/local-pg_hba.conf /etc/postgresql/9.4/main/pg_hba.conf
sudo /etc/init.d/postgresql restart
