#!/usr/bin/env bash
pushd .

sudo rm -rf /tmp/redis-3.0.7

sudo mkdir /etc/redis
sudo mkdir -p /var/redis/6379

cd /tmp
wget http://download.redis.io/releases/redis-3.0.7.tar.gz
tar xzf redis-3.0.7.tar.gz
cd redis-3.0.7
make
sudo make install

sudo cp utils/redis_init_script /etc/init.d/redis_6379
sudo cp /vagrant/vagrant-files/redis/6379.conf /etc/redis/
sudo update-rc.d redis_6379 defaults
sudo /etc/init.d/redis_6379 start

rm /tmp/redis-3.0.7.tar.gz
rm -rf /tmp/redis-3.0.7

popd
