# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20160218_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("subscribe", "subscribe"),
                    ("unsubscribe", "unsubscribe"),
                    ("trigger", "trigger"),
                    ("update", "update"),
                ],
                max_length=255,
            ),
        ),
    ]
