# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20160303_1418"),
        ("core", "0008_auto_20160322_0908"),
    ]

    operations = []
