# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20180726_1558"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptoutHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sailthru_optout",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("all", "Optout (All)"),
                            ("basic", "Optout (Basic)"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(help_text="Explanatory supporting text.")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
        migrations.AddField(
            model_name="audienceuser",
            name="sailthru_optout",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("all", "Optout (All)"),
                    ("basic", "Optout (Basic)"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="optouthistory",
            name="audience_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optout_history",
                to="core.AudienceUser",
            ),
        ),
    ]
