# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20190322_0835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontenthistory",
            name="referrer",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
