# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-08-24 16:40
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190322_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionlog',
            options={},
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usercontenthistory',
            name='referrer',
            field=core.fields.ReferrerField(blank=True, max_length=500, null=True),
        ),
    ]
