# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2022-12-20 16:51
from __future__ import unicode_literals

import core.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211007_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[(b'Defense One', b'Defense One'), (b'Govexec', b'Govexec'), (b'Nextgov', b'Nextgov'), (b'Route Fifty', b'Route Fifty'), (b'Federal Soup', b'Federal Soup'), (b'FCW', b'FCW'), (b'Washington Technology', b'Washington Technology'), (b'GCN', b'GCN'), (b'Defense Systems', b'Defense Systems'), (b'GMarkU', b'GMarkU'), (b'Military Periscope', b'Military Periscope'), (b'Forecast International', b'Forecast International'), (b'The Atlas Market Edge', b'The Atlas Market Edge')], max_length=255),
        ),
    ]
