# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:40
from __future__ import unicode_literals

from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def add_perms(apps, schema_editor):
    # Hacky way to ensure that permissions are added by this point. See:
    # https://code.djangoproject.com/ticket/23422
    emit_post_migrate_signal(verbosity=0, interactive=False, db=schema_editor.connection.alias)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    perms = Permission.objects.filter(content_type__app_label="sailthru_sync")

    group = Group.objects.get(name="Administrator")
    group.permissions.add(*perms)


def remove_perms(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    perms = Permission.objects.filter(content_type__app_label="sailthru_sync")
    Group.objects.get(name="Administrator").permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('sailthru_sync', '0001_initial'),
        ('core', '0008_auto_20160322_0908'),
    ]

    operations = [
        migrations.RunPython(add_perms, remove_perms),
    ]
