# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 18:10
from __future__ import unicode_literals

from django.db import migrations


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Cron = apps.get_model('djcelery', 'CrontabSchedule')
    PeriodicTask = apps.get_model('djcelery', 'PeriodicTask')

    NotificationGroup = apps.get_model('sailthru_sync', 'SyncFailureNotificationGroup')

    auth_group = Group.objects.create(name='Sailthru sync failure')

    cron = Cron.objects.create(minute=5, hour="*", day_of_week="*", day_of_month="*", month_of_year="*")
    periodic_task = PeriodicTask.objects.create(
        name='Notify on new Sailthru sync failures.',
        task='sailthru_sync.tasks.send_sync_failure_notifications',
        enabled=True,
        crontab=cron,
    )

    invalid_email = '11'
    NotificationGroup.objects.create(
        interested_group=auth_group,
        notification_task=periodic_task,
        interested_errors=[invalid_email],
    )


def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    NotificationGroup = apps.get_model('sailthru_sync', 'SyncFailureNotificationGroup')

    auth_group = Group.objects.filter(name='Sailthru sync failure')
    notification_groups = NotificationGroup.objects.filter(interested_group=auth_group)

    for g in notification_groups:
        g.notification_task.crontab.delete()
        g.notification_task.delete()
        g.delete()
        auth_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sailthru_sync', '0004_syncfailurenotificationgroup'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups),
    ]
